### ISSUE TITLE
Profile - Error message on uploading profile picture

### ISSUE THREAD

**Issue by init-five** [init-five/Smart-Cut-Portal#1]
**Screenshot**

![Image](https://github.com/init-five/Smart-Cut-Portal/assets/78718349/a5517540-1711-4026-b885-bb193d14f0a0)

**API**

![Image](https://github.com/init-five/Smart-Cut-Portal/assets/78718349/cad96650-42c1-4073-a282-631a3a50c2de)

**Comment by Wali-Ullah-Asim** [comment]
This issue is fixed because we don't have a profile tab in the section.
