### ISSUE TITLE
Profile - Error message on deleting profile picture

### ISSUE THREAD

**Issue by init-five** [init-five/Smart-Cut-Portal#2]
**Screenshot**

![Image](https://github.com/init-five/Smart-Cut-Portal/assets/78718349/b658c385-9c9d-4c61-b71b-b3bbd8b953b9)

**API**

![Image](https://github.com/init-five/Smart-Cut-Portal/assets/78718349/367ae99f-31d3-4b3c-9823-c216a458ae5f)

**Comment by Wali-Ullah-Asim** [comment]
This issue is fixed because we don't have a profile tab anymore.
