### ISSUE TITLE
Settings - Salon Basic Details - Updating information is not working

### ISSUE THREAD

**Issue by init-five** [init-five/Smart-Cut-Portal#4]
**Screenshot**

![Image](https://github.com/init-five/Smart-Cut-Portal/assets/78718349/cd3927ff-b43f-4431-bdb3-ab0e74012b67)

**API**

![Image](https://github.com/init-five/Smart-Cut-Portal/assets/78718349/efcda8e9-2780-4cc9-83a8-483044f21c7f)

**Comment by Wali-Ullah-Asim** [comment]
This issue is fixed and deployed
