### ISSUE TITLE
Banner - Add max character limit for Banner Title

### ISSUE THREAD

**Issue by init-five** [init-five/Smart-Cut-Portal#7]
**Screenshot**

![Image](https://github.com/init-five/Smart-Cut-Portal/assets/78718349/e4613985-0740-4893-bdb1-cb413a215870)

**Comment by Wali-Ullah-Asim** [comment]
This issue is fixed

**Comment by init-five** [comment]
@Wali-Ullah-Asim UI is still breaking 


![Image](https://github.com/init-five/Smart-Cut-Portal/assets/78718349/bf274d88-bd46-4d85-8a8b-61a776d81f8b)
